root = "."
tmp_dir = ".air"

[build]
  cmd = "echo skipping build"
  bin = ""
  full_bin = "go run ./cmd/main/main.go"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules", "test_data/uploads"]
  delay = 800
  log = "air.log"
  stop_on_error = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"


