// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cars.sql

package database

import (
	"context"
)

const getAllCars = `-- name: GetAllCars :many
select id, last_name, number, checked_in from cars
`

func (q *Queries) GetAllCars(ctx context.Context) ([]Car, error) {
	rows, err := q.query(ctx, q.getAllCarsStmt, getAllCars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Car
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.Number,
			&i.CheckedIn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckedIn = `-- name: UpdateCheckedIn :exec
update cars set checked_in = ? where id = ?
`

type UpdateCheckedInParams struct {
	CheckedIn interface{} `json:"checked_in"`
	ID        string      `json:"id"`
}

func (q *Queries) UpdateCheckedIn(ctx context.Context, arg UpdateCheckedInParams) error {
	_, err := q.exec(ctx, q.updateCheckedInStmt, updateCheckedIn, arg.CheckedIn, arg.ID)
	return err
}
