// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cars.sql

package database

import (
	"context"
)

const getAllCars = `-- name: GetAllCars :exec
select id, last_name, number, checked_in from cars
`

func (q *Queries) GetAllCars(ctx context.Context) error {
	_, err := q.exec(ctx, q.getAllCarsStmt, getAllCars)
	return err
}

const updateCheckedIn = `-- name: UpdateCheckedIn :exec
update cars set checked_in = ? where id = ?
`

type UpdateCheckedInParams struct {
	CheckedIn interface{} `json:"checked_in"`
	ID        string      `json:"id"`
}

func (q *Queries) UpdateCheckedIn(ctx context.Context, arg UpdateCheckedInParams) error {
	_, err := q.exec(ctx, q.updateCheckedInStmt, updateCheckedIn, arg.CheckedIn, arg.ID)
	return err
}
