// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Car struct {
	ID        string      `json:"id"`
	LastName  string      `json:"last_name"`
	Number    int64       `json:"number"`
	CheckedIn interface{} `json:"checked_in"`
}
